### ISSUE TITLE
Output dir already exists

### ISSUE THREAD

**Issue by l4t3b0** [juzraai/dijnet-bot#12]
Szia

Készítek egy [docker image-et](https://github.com/l4t3b0/docker-dijnet-bot) az alkalmazásod köré, hogy rendszeresen cron segítségével automatikusan szinkronizálhassam a számláimat.

**Mi történt? Mit tapasztaltál?**
Tesztelés miatt beállítottam, hogy ma este óránként fusson le a szinkronizáció. Ma reggel kiértékeltem a logokat és azt láttam, hogy hajnali 4-ig tök jól futott az alkalmazás és az alábbi logrészleteket kaptam:
```
2020-10-31 4:00:00 AM | DíjnetBot v2.1.6 by juzraai | https://github.com/juzraai/dijnet-bot
2020-10-31 4:00:00 AM | Könyvtár létrehozása: /data
2020-10-31 4:00:00 AM | Kész-lista beolvasása: /data/kesz.txt
2020-10-31 4:00:00 AM | 17 db számla van a kimeneti mappában
2020-10-31 4:00:00 AM | Bejelentkezés...
2020-10-31 4:00:00 AM | 3s várakozás...
2020-10-31 4:00:03 AM | POST https://www.dijnet.hu/ekonto/login/login_check_password
2020-10-31 4:00:03 AM | Bejelentkezve: ****************
2020-10-31 4:00:03 AM | Számlák keresése...
2020-10-31 4:00:03 AM | 3s várakozás...
2020-10-31 4:00:06 AM | GET https://www.dijnet.hu/ekonto/control/szamla_search
2020-10-31 4:00:07 AM | 3s várakozás...
2020-10-31 4:00:10 AM | POST https://www.dijnet.hu/ekonto/control/szamla_search_submit
2020-10-31 4:00:10 AM | 16 db számla van a rendszerben: 0 db új, 16 db lementve korábban
2020-10-31 4:00:10 AM | 0 db új számla lementve!
```
Itt már van egy érdekesség, hogy 17 számlám van, de a végén 16 van lementve és 0 db új!!!

Majd 5-kor elkezdtek jönni a probléma:
```
2020-10-31 5:00:00 AM | DíjnetBot v2.1.6 by juzraai | https://github.com/juzraai/dijnet-bot
2020-10-31 5:00:00 AM | Könyvtár létrehozása: /data
2020-10-31 5:00:00 AM | EEXIST: file already exists, mkdir '/data'
2020-10-31 5:00:00 AM |
2020-10-31 5:00:00 AM | Ha biztos vagy abban, hogy helyesen konfiguráltad a Díjnet Bot-ot, akkor a hiba a programban lehet.
2020-10-31 5:00:00 AM | Kérlek, az alábbi linken nyiss egy új issue-t, másold be a hiba részleteit, és írd le röviden, milyen szituációban jelentkezett a hiba!
2020-10-31 5:00:00 AM |
2020-10-31 5:00:00 AM | -->  https://github.com/juzraai/dijnet-bot/issues
2020-10-31 5:00:00 AM |
2020-10-31 5:00:00 AM |
2020-10-31 5:00:00 AM | A hiba részletei:
2020-10-31 5:00:00 AM | Error: EEXIST: file already exists, mkdir '/data'
2020-10-31 5:00:00 AM |     at Object.mkdirSync (fs.js:921:3)
2020-10-31 5:00:00 AM |     at mkdirpManualSync (/tmp/dijnet-bot-2.1.6/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
2020-10-31 5:00:00 AM |     at mkdirpNativeSync (/tmp/dijnet-bot-2.1.6/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
2020-10-31 5:00:00 AM |     at mkdirpSync (/tmp/dijnet-bot-2.1.6/node_modules/mkdirp/index.js:21:7)
2020-10-31 5:00:00 AM |     at Repo.init (/tmp/dijnet-bot-2.1.6/src/repo.js:31:3)
2020-10-31 5:00:00 AM |     at start (/tmp/dijnet-bot-2.1.6/src/main.js:16:40)
2020-10-31 5:00:00 AM |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Milyen szituációban? Hogyan futtattad a programot? Hogyan tudom reprodukálni a hibát?**
Docker-ben futtatom. Van esély rá, hogy futtass docker-t? Ha nem, akkor esetleg egy debug verziót tudnék én futtatni, hogy több log legyen.

**Mi lenne az elvárt működés? Minek kellett volna történnie?**
Létezik a /data könyvtár és ez normális. Miért dob erre hibát?

**error.log fájl tartalma**
Fent ott van már mindkét log file.

**Rendszerinformáció**
 - Operációs rendszer: Linux ([Unraid 6.8.3](https://unraid.net/))
 - Node verzió: v12.18.4
 - Program verzió: v2.1.6

**Comment by juzraai** [comment]
Wow! Örülök, hogy még valakinek hasznos a cucc és hogy még építkezel is rá. :)

Köszi a részletes hibaleírást is, érdekes mindkét bug (output dir és a különböző darabszámok)! Igyekszem ránézni. Dockert tudok futtatni, persze. :)

**Comment by l4t3b0** [comment]
Szia

Már bocsánatot is kell kérnem sajnos. Egy időzített script jogosultságanomáliát csinált és az okozta, hogy nem tudja létrehozni a könyvtárat.

A 16 vs 17 kapcsán:
Nem elképzelhető, hogy a "kesz.txt"-t is számlának számolja a program?

**Comment by juzraai** [comment]
Semmi gond, annyival könnyebb a dolgom. :)

16 vs 17:

A program a futás elején a `kesz.txt`-ben levő **sorok számát írja** ki egész egyszerűen :), mert minden számlaazonosítót 1 sorban tárol le ebben a fájlban. Volt ezzel bug korábban, hogy Díjnetről több soros azonosítók jöttek, de elvileg megoldottam ezt már - #3 (konkrétan kidobálom az összes sortörést belőlük).

Tudnád kérlek ellenőrizni, hogy `wc -l kesz.txt` tényleg 17-et ír-e ki?

Illetve meg tudnád nézni kérlek, hogy nincs-e a `kesz.txt`-ben valami gyanús dolog? Pl. egy számlaazonosító 2x? Vagy valami fura sor, ami nem egy egész számlaazonosító?

(Számlaazonosító = a számla sorszáma, az XML és a PDF is tartalmazza, pl. "FCS/00000000")

**Comment by l4t3b0** [comment]
root@Tatooine:/mnt/user/Tmp/dijnet-bot# wc -l kesz.txt
16 kesz.txt
root@Tatooine:/mnt/user/Tmp/dijnet-bot# cat kesz.txt
151009779757
FVM/83613541
88730129
151009489750
151009296397
DFR/23145246
FVM/82847624
88570468
151009090264
151008879167
DFR/22953312
151008670837
DFR/22860514
151008462194
DFR/22763929
151008254199
root@Tatooine:/mnt/user/Tmp/dijnet-bot#

**Comment by l4t3b0** [comment]
```
root@Tatooine:/mnt/user/Tmp/dijnet-bot# hexdump -c kesz.txt
0000000   1   5   1   0   0   9   7   7   9   7   5   7  \n   F   V   M
0000010   /   8   3   6   1   3   5   4   1  \n   8   8   7   3   0   1
0000020   2   9  \n   1   5   1   0   0   9   4   8   9   7   5   0  \n
0000030   1   5   1   0   0   9   2   9   6   3   9   7  \n   D   F   R
0000040   /   2   3   1   4   5   2   4   6  \n   F   V   M   /   8   2
0000050   8   4   7   6   2   4  \n   8   8   5   7   0   4   6   8  \n
0000060   1   5   1   0   0   9   0   9   0   2   6   4  \n   1   5   1
0000070   0   0   8   8   7   9   1   6   7  \n   D   F   R   /   2   2
0000080   9   5   3   3   1   2  \n   1   5   1   0   0   8   6   7   0
0000090   8   3   7  \n   D   F   R   /   2   2   8   6   0   5   1   4
00000a0  \n   1   5   1   0   0   8   4   6   2   1   9   4  \n   D   F
00000b0   R   /   2   2   7   6   3   9   2   9  \n   1   5   1   0   0
00000c0   8   2   5   4   1   9   9  \n
00000c8
root@Tatooine:/mnt/user/Tmp/dijnet-bot# hexdump -x kesz.txt
0000000    3531    3031    3930    3737    3739    3735    460a    4d56
0000010    382f    3633    3331    3435    0a31    3838    3337    3130
0000020    3932    310a    3135    3030    3439    3938    3537    0a30
0000030    3531    3031    3930    3932    3336    3739    440a    5246
0000040    322f    3133    3534    3432    0a36    5646    2f4d    3238
0000050    3438    3637    3432    380a    3538    3037    3634    0a38
0000060    3531    3031    3930    3930    3230    3436    310a    3135
0000070    3030    3838    3937    3631    0a37    4644    2f52    3232
0000080    3539    3333    3231    310a    3135    3030    3638    3037
0000090    3338    0a37    4644    2f52    3232    3638    3530    3431
00000a0    310a    3135    3030    3438    3236    3931    0a34    4644
00000b0    2f52    3232    3637    3933    3932    310a    3135    3030
00000c0    3238    3435    3931    0a39
00000c8
root@Tatooine:/mnt/user/Tmp/dijnet-bot#
```

**Comment by juzraai** [comment]
Banális hiba volt, javítottam #14 -ben, frissíts kérlek a v2.1.7 -re. :)

Ezt a ticketet is zárom akkor, mert a mappa létrehozási problémát más okozta. :)
