### ISSUE TITLE
unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1942: 

### ISSUE THREAD

**Issue by rostasc3** [juzraai/dijnet-bot#16]
Szia, 
bocsi, csak le akartam menteni a számláimat, de kidobta ezt a hibát. A node.js nem ismerős számomra, így idemásolom a logot. A gépem win10 home 64bit. Előzőleg sikeresen működött a dijnet-bot.

2020-12-31 20:27:01: write EPROTO 3980:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1942:

RequestError: write EPROTO 3980:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:c:\ws\deps\openssl\openssl\ssl\statem\statem_lib.c:1942:

    at ClientRequest.<anonymous> (d:\dijnet-bot-master\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (d:\dijnet-bot-master\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

köszönöm!
István

**Comment by juzraai** [comment]
Köszi a hibajelzést, igyekszem ránézni. :)

**Comment by juzraai** [comment]
Ránéztem, működnie kéne. Megpróbálnád megint? Hátha valami ideiglenes probléma volt.

Ha nem megy, ellenőrizd lécci a Node.js verziódat (parancssorban `node -v` parancs), fontos, hogy legalább v12 legyen.

Esetleg próbáld meg a Releases alól leszedni az [összecsomagolt JS fájlt](https://github.com/juzraai/dijnet-bot/releases/download/v2.1.7/dijnet-bot.js), és azt futtatni (`node dijnet-bot.js`).

Amit még meg lehet próbálni, hogy a `--tls-min-v1.0` kapcsolóval futtatod:

```
node --tls-min-v1.0 dijnet-bot.js
```

---

Jegyzet magamnak: possibly related nodejs/help#1936 + https://stackoverflow.com/a/56319636/2418224

**Comment by rostasc3** [comment]
Szia Zsolt,
köszönöm szépen a segítséget, az összecsomagolt js file futtatása volt a
megoldás.

node --tls-min-v1.0 dijnet-bot.js

A node verzióm 14.15.3, mert amikor elsőre nem működött (az, ami
régebben tökéletes volt), frissítettem a node-t a legújabbra.
A --tls-min-v1.0 index.js futtatása certificate has expired-et adott,
de az összecsomagolt újra jó!

Köszönöm és boldog új évet kívánok!

István


Zsolt Jurányi <notifications@github.com> ezt írta (időpont: 2021. jan. 1.,
P, 12:06):

**Comment by juzraai** [comment]
Nincs mit, szívesen, örülök, hogy működik. :) Boldog új évet! :)
