### ISSUE TITLE
GotError: getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by NyariG** [juzraai/dijnet-bot#34]
**Mi történt? Mit tapasztaltál?**
root@pve:~# /usr/bin/node dijnet-bot.js
2024-01-05 11:32:49 AM | DíjnetBot v2.1.9 by juzraai | https://github.com/juzraai/dijnet-bot
2024-01-05 11:32:49 AM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak
2024-01-05 11:32:49 AM | Kész-lista beolvasása: /mnt/pve/SMB/Számlák/szamlak/kesz.txt
2024-01-05 11:32:49 AM | 54 db számla van a kimeneti mappában
2024-01-05 11:32:49 AM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak/.temp
2024-01-05 11:32:49 AM | Bejelentkezés...
2024-01-05 11:32:49 AM | 3s várakozás...
2024-01-05 11:32:52 AM | POST https://www.dijnet.hu/ekonto/login/login_check_password

getaddrinfo EAI_AGAIN www.dijnet.hu

Ha biztos vagy abban, hogy helyesen konfiguráltad a Díjnet Bot-ot, akkor a hiba a programban lehet.
Kérlek, az alábbi linken nyiss egy új issue-t, másold be a hiba részleteit, és írd le röviden, milyen szituációban jelentkezett a hiba!

-->  https://github.com/juzraai/dijnet-bot/issues

A hiba részleteit megtalálod a(z) ./error.log fájlban.r

**Milyen szituációban? Hogyan futtattad a programot? Hogyan tudom reprodukálni a hibát?**
...Proxmox shelljében futtatnám. egy Chron segitségével.

**Mi lenne az elvárt működés? Minek kellett volna történnie?**
...Bejelentkezik és letölti a számlákat. 

**error.log fájl tartalma**
```
2024-01-05 11:33:11 AM: getaddrinfo EAI_AGAIN www.dijnet.hu
GotError: getaddrinfo EAI_AGAIN www.dijnet.hu
    at a (/root/dijnet-bot.js:10:206986)
    at p (/root/dijnet-bot.js:10:207367)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
```

**Rendszerinformáció**
 - Operációs rendszer:  Proxmox 8.0.3
 - Node verzió: 
 - Program verzió: ?

Ami még furcsa:
-Van amikor bejelentkezik ki is irja hogy még 50 számlát kell letölteni nekiáll, de 2-3 után lehal.
-a .env filében én átirtam 1s re a várakozási idöt, de ugyan ugy 3s el dolgozik. Viszont a hely adatokat onnan szedi:

```
# Díjnet bejelentkezési adatok:
DIJNET_USER=cxxxxxxxx
DIJNET_PASS=sxxxxxx


# Kimeneti mappa, ahova a számlák fájljai kerüljenek:
OUTPUT_DIR=/mnt/pve/SMB/Számlák/szamlak


# Segédfájlok mappája:
# Ha nem adod meg (kommentként hagyod) vagy üres értéket adsz neki, akkor nem
# lesznek ilyen fájlok kimentve. Akkor érdemes bekapcsolni, ha valami hibát dob
# a program, a kimentett HTML fájlok segíthetnek a probléma javításában.
TEMP_DIR=/mnt/pve/SMB/Számlák/szamlak/.temp


# Késleltetés a Díjnetnek küldött kérések előtt (másodpercben):
# Erre azért van szükség, hogy kevésbé terheljük a szervert. Javallott 3-5
# másodperces értéket beállítani.
SLEEP=1


# Naplózás módja:
# default = terminálban könnyen érthető folyamatjelző, fájlba irányítva bővített napló (korábban: LOG_LEVEL=1/2)
# verbose = bővített napló, minden műveletről tájékoztat (korábban: LOG_LEVEL=4)
# quiet = nincs kimenet (korábban: LOG_LEVEL=0)
LOG_MODE=verbose
```

**Comment by juzraai** [comment]
Köszi a hibajelzést!

Raktam ki [egy új, v2.1.10-es verziót](https://github.com/juzraai/dijnet-bot/releases/tag/v2.1.10), kérlek próbáld meg azzal. Beépítettem egy DNS gyorsítótárat, ami remélhetőleg megoldja az EAI_AGAIN problémát.

A késleltetés minimálisan 3 másodperc, ez szándékos. :)

**Comment by NyariG** [comment]
Hallo, köszi kiprobáltam de most eddig jut el:

root@pve:~# /usr/bin/node dijnet-bot.js
2024-01-08 8:48:32 AM | DíjnetBot v2.1.10 by juzraai | https://github.com/juzraai/dijnet-bot
2024-01-08 8:48:32 AM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak
2024-01-08 8:48:32 AM | Kész-lista beolvasása: /mnt/pve/SMB/Számlák/szamlak/kesz.txt
2024-01-08 8:48:32 AM | 67 db számla van a kimeneti mappában
2024-01-08 8:48:32 AM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak/.temp
2024-01-08 8:48:32 AM | Bejelentkezés...
2024-01-08 8:48:32 AM | 4s várakozás...
2024-01-08 8:48:36 AM | POST https://www.dijnet.hu/ekonto/login/login_check_password
2024-01-08 8:48:42 AM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024010884842__login_login_check_password.html
2024-01-08 8:48:42 AM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024010884842__login_login_check_password.cookies
2024-01-08 8:48:42 AM | Bejelentkezve: cs******
2024-01-08 8:48:42 AM | Számlák keresése...
2024-01-08 8:48:42 AM | 4s várakozás...
2024-01-08 8:48:46 AM | GET https://www.dijnet.hu/ekonto/control/szamla_search
2024-01-08 8:48:46 AM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024010884846__control_szamla_search.html
2024-01-08 8:48:46 AM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024010884846__control_szamla_search.cookies
2024-01-08 8:48:46 AM | 4s várakozás...
2024-01-08 8:48:50 AM | POST https://www.dijnet.hu/ekonto/control/szamla_search_submit

queryA ETIMEOUT www.dijnet.hu

Ha biztos vagy abban, hogy helyesen konfiguráltad a Díjnet Bot-ot, akkor a hiba a programban lehet.
Kérlek, az alábbi linken nyiss egy új issue-t, másold be a hiba részleteit, és írd le röviden, milyen szituációban jelentkezett a hiba!

-->  https://github.com/juzraai/dijnet-bot/issues

A hiba részleteit megtalálod a(z) ./error.log fájlban.



ez az error file:

2024-01-08 8:51:20 AM: queryA ETIMEOUT www.dijnet.hu
GotError: queryA ETIMEOUT www.dijnet.hu
    at a (/root/dijnet-bot.js:10:206986)
    at p (/root/dijnet-bot.js:10:207367)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:47:19)

**Comment by kodfodrasz** [comment]
Ez a módosítás valamiféle regressziót okozott.

## Környezet

- Fedora 39
- node v20.10.0

## dijnet-bot v.2.1.9

~~~
node dijnet-bot-v2.1.9.js
DíjnetBot v2.1.9 by juzraai | https://github.com/juzraai/dijnet-bot

Bejelentkezve: <username törölve>
133 db számla van a rendszerben: 0 db új, 133 db lementve korábban
0 db új számla lementve!
~~~

## dijnet-bot v.2.1.10

~~~
node dijnet-bot-v2.1.10.js
DíjnetBot v2.1.10 by juzraai | https://github.com/juzraai/dijnet-bot

Bejelentkezés...
queryAaaa ENODATA www.dijnet.hu

Ha biztos vagy abban, hogy helyesen konfiguráltad a Díjnet Bot-ot, akkor a hiba a programban lehet.
Kérlek, az alábbi linken nyiss egy új issue-t, másold be a hiba részleteit, és írd le röviden, milyen szituációban jelentkezett a hiba!

-->  https://github.com/juzraai/dijnet-bot/issues

A hiba részleteit megtalálod a(z) ./error.log fájlban.⏎
~~~

## error.log
~~~
2024-01-10 6:52:05 PM: queryAaaa ENODATA www.dijnet.hu
GotError: queryAaaa ENODATA www.dijnet.hu
    at a (/home/user/tmp/dijnet/dijnet-bot-v2.1.10.js:10:206986)
    at p (/home/user/tmp/dijnet/dijnet-bot-v2.1.10.js:10:207367)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:45:19)⏎
~~~

a díjnet AAAA rekord (ipv6) hiánya miatt van látszólat, de a node `--dns-result-order=ipv4first` -et próbáltam, nem működött, downgradeltem egyelőre (gépek közti költöztetés és frissítés során tűnt fel a hiba)

**Comment by juzraai** [comment]
Köszi a hibajelzést neked is! Ezt reprodukálni tudom Node v20-on, viszont Node v16-on nincs ilyen gond.

Szóval az megoldás lehet talán mindkettőtöknek, ha Node v16-ot telepítetek v20 helyett, vagy mellé (pl. [NVM](https://github.com/nvm-sh/nvm)-mel), és azzal futtatjátok a programot.

Ezek a hibák kissé feladják a leckét most, de utána fogok járni valamikor.

**Comment by juzraai** [comment]
No, átdrótoztam a progit Node v20-ra, itt az új [v3.0.0](https://github.com/juzraai/dijnet-bot/releases/tag/v3.0.0). Ezzel az utolsó problémát már nem tudtam reprodukálni. Remélhetőleg a korábbi problémák is megoldódnak.

**Comment by kodfodrasz** [comment]
> No, átdrótoztam a progit Node v20-ra, itt az új [v3.0.0](https://github.com/juzraai/dijnet-bot/releases/tag/v3.0.0). Ezzel az utolsó problémát már nem tudtam reprodukálni. Remélhetőleg a korábbi problémák is megoldódnak.

Működik!

Van egy warning (nem a releaset futtatom, hanem a tagből kicheckolt gitet)

```(node:36) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

Ami a javasolt opcióval futtatva ezt adja. 

```[root@da97b4c941ab dijnet-bot]# node --trace-warnings index.js
(node:25) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
    at emitExperimentalWarning (node:internal/util:275:11)
    at ModuleLoader.jsonStrategy (node:internal/modules/esm/translators:453:3)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30)
DíjnetBot v3.0.0 by juzraai | https://github.com/juzraai/dijnet-bot

[...]
```

**Comment by juzraai** [comment]
A [v3.0.1](https://github.com/juzraai/dijnet-bot/releases/tag/v3.0.1)-ben javítottam most a warning-ot, meg a bundle generálást is (a v3.0.0 release-ben levő fájl nem működött).

**Comment by kodfodrasz** [comment]
> A [v3.0.1](https://github.com/juzraai/dijnet-bot/releases/tag/v3.0.1)-ben javítottam most a warning-ot, meg a bundle generálást is (a v3.0.0 release-ben levő fájl nem működött).

Nálam tökéletesen működik ez a verzió! Köszi!

**Comment by NyariG** [comment]
Hát nálam még mindig nem jó, de akkor valószinü hogy nálam van a baj:

root@pve:~# /usr/bin/node dijnet-bot.cjs
2024-01-22 4:58:22 PM | DíjnetBot v3.0.1 by juzraai | https://github.com/juzraai/dijnet-bot
2024-01-22 4:58:22 PM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak
2024-01-22 4:58:22 PM | Kész-lista beolvasása: /mnt/pve/SMB/Számlák/szamlak/kesz.txt
2024-01-22 4:58:22 PM | 67 db számla van a kimeneti mappában
2024-01-22 4:58:22 PM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak/.temp
2024-01-22 4:58:22 PM | Bejelentkezés...
2024-01-22 4:58:22 PM | 4s várakozás...
2024-01-22 4:58:26 PM | POST https://www.dijnet.hu/ekonto/login/login_check_password
2024-01-22 4:58:36 PM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012245836__login_login_check_password.html
2024-01-22 4:58:36 PM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012245836__login_login_check_password.cookies
2024-01-22 4:58:36 PM | Bejelentkezve: c.................
2024-01-22 4:58:36 PM | Számlák keresése...
2024-01-22 4:58:36 PM | 4s várakozás...
2024-01-22 4:58:40 PM | GET https://www.dijnet.hu/ekonto/control/szamla_search
2024-01-22 4:58:40 PM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012245840__control_szamla_search.html
2024-01-22 4:58:40 PM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012245840__control_szamla_search.cookies
2024-01-22 4:58:40 PM | 4s várakozás...
2024-01-22 4:58:44 PM | POST https://www.dijnet.hu/ekonto/control/szamla_search_submit
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ne [RequestError]: getaddrinfo EAI_AGAIN www.dijnet.hu
    at ClientRequest.<anonymous> (/root/dijnet-bot.cjs:156:40963)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:529:35)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  input: undefined,
  code: 'EAI_AGAIN',
  timings: {
    start: 1705939124628,
    socket: 1705939124629,
    lookup: 1705939160664,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1705939160665,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 36035,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 36037
    }
  },
  options: t {
    _unixOptions: undefined,
    _internals: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: undefined,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: 'vfw_form=szamla_search_submit&vfw_coll=szamla_search_params&regszolgid=&szlaszolgid=&datumtol=&datumig=',
      form: undefined,
      json: undefined,
      cookieJar: t {
        rejectPublicSuffixes: true,
        enableLooseMode: false,
        allowSpecialUseDomain: true,
        store: bs {
          synchronous: true,
          idx: [Object: null prototype] {
            'www.dijnet.hu': [Object: null prototype],
            'dijnet.hu': [Object: null prototype]
          },
          [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
        },
        prefixSecurity: 'silent',
        _cloneSync: [Function (anonymous)],
        _importCookiesSync: [Function (anonymous)],
        getCookiesSync: [Function (anonymous)],
        getCookieStringSync: [Function (anonymous)],
        getSetCookieStringsSync: [Function (anonymous)],
        removeAllCookiesSync: [Function (anonymous)],
        setCookieSync: [Function (anonymous)],
        serializeSync: [Function (anonymous)]
      },
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'accept-language': 'hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7',
        'content-type': 'application/x-www-form-urlencoded',
        'content-length': '103',
        'accept-encoding': 'gzip, deflate, br',
        cookie: 'JSESSIONID=...; lang=hu; HAPROXY_SESSION=...'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'POST',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: 'latin1',
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: URL {
        [Symbol(context)]: URLContext {
          href: 'https://www.dijnet.hu/ekonto/control/szamla_search_submit',
          protocol_end: 6,
          username_end: 8,
          host_start: 8,
          host_end: 21,
          pathname_start: 21,
          search_start: 4294967295,
          hash_start: 4294967295,
          port: 4294967295,
          scheme_type: 2
        }
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: false
    },
    _merging: false,
    _init: [
      {
        cookieJar: t {
          rejectPublicSuffixes: true,
          enableLooseMode: false,
          allowSpecialUseDomain: true,
          store: bs {
            synchronous: true,
            idx: [Object: null prototype],
            [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
          },
          prefixSecurity: 'silent',
          _cloneSync: [Function (anonymous)],
          _importCookiesSync: [Function (anonymous)],
          getCookiesSync: [Function (anonymous)],
          getCookieStringSync: [Function (anonymous)],
          getSetCookieStringsSync: [Function (anonymous)],
          removeAllCookiesSync: [Function (anonymous)],
          setCookieSync: [Function (anonymous)],
          serializeSync: [Function (anonymous)]
        },
        encoding: 'latin1',
        method: 'POST',
        headers: {
          accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
          'accept-language': 'hu-HU,hu;q=0.9,en-US;q=0.8,en;q=0.7',
          'content-type': 'application/x-www-form-urlencoded'
        },
        body: 'vfw_form=szamla_search_submit&vfw_coll=szamla_search_params&regszolgid=&szlaszolgid=&datumtol=&datumig='
      }
    ]
  }
}

Node.js v18.19.0

**Comment by kodfodrasz** [comment]
Milyen DNS szervert használsz?

Nekem a gépen amin fut az unbound caching dns proxy fut, és azt használja a rendszer. Upstream DNS-nek a cloudfare féle 1.1.1.1 -et használom, mert hazai ISP-k DNS szervereivel korábban rendszeresen voltak problémáim.


`dig dijnet.hu` mit mond? (futtasd többször, hátha ott is előjön a tranziens hiba)

**Comment by NyariG** [comment]
1.1.1.1-et használok.

ezt adja:

root@pve:~# cat /etc/resolv.conf
search local
nameserver 1.1.1.1
nameserver 8.8.4.4
nameserver 8.8.8.8
root@pve:~# dig dijnet.hu
;; communications error to 1.1.1.1#53: timed out

; <<>> DiG 9.18.16-1~deb12u1-Debian <<>> dijnet.hu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5298
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dijnet.hu.                     IN      A

;; ANSWER SECTION:
dijnet.hu.              85225   IN      A       91.198.198.5

;; Query time: 136 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Tue Jan 23 09:40:55 CET 2024
;; MSG SIZE  rcvd: 43


csináltam egy traceroutot is hátha mond valamit:

root@pve:~# traceroute dijnet.hu
traceroute to dijnet.hu (91.198.198.5), 30 hops max, 60 byte packets
 1  * * *
 2  lo1.bsr1-szombathely.net.telekom.hu (145.236.238.213)  2.842 ms  3.125 ms  3.080 ms
 3  84.1.66.118 (84.1.66.118)  9.207 ms 84.1.66.116 (84.1.66.116)  7.492 ms 84.1.66.120 (84.1.66.120)  10.394 ms
 4  81.183.0.37 (81.183.0.37)  7.395 ms  7.351 ms  7.306 ms
 5  81.183.2.199 (81.183.2.199)  7.260 ms 81.183.3.12 (81.183.3.12)  7.743 ms 84.2.229.225 (84.2.229.225)  7.698 ms
 6  84.2.229.225 (84.2.229.225)  7.651 ms  7.485 ms  6.931 ms
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
root@pve:~#

**Comment by kodfodrasz** [comment]
Ez is timeoutolt, érdekes. Valami a hálózatodon nem kerek. Wifin csatlakozik a gép? Van packet drop? Vagy a hálózatodon kívül van packet drop esetleg? Valami nagy forgalom fut esetleg QoS nélkül, teljesen "kimaxolva a csövet"? 

`/etc/resolv.conf` -ban a timeoutot tudod megnövelni első körben (de ezt rebootnál felülírhatja a rendszer, ha systemd generált)

~~~
#/etc/resolv.conf
# timeout, default 5sec. max 30.
options timeout 10
~~~

Egy caching dns proxyt belőhetsz esetleg, hogy javítson a helyzeten (én azért használok unboundot mert nagyon könnyű bekonfigolni). Más ötletem nincs, de ez hálózati gondnak tűnik. Vagy QoS-t a routeren, a DNS kéréseket priorizálva, de ez már a bonyolultabb kategória szerintem. Lehet, hogy a szolgáltató vacakol, akkor náluk is érdemes reklamálni, ha nagy a packet loss.

**Comment by NyariG** [comment]
Most átállitottam a node ot a v16 ról a v20.11 re igy lefut, de igy meg nem taläl egy számlát sem:  
root@pve:~# /usr/bin/node dijnet-bot.cjs
2024-01-25 3:42:31 PM | DíjnetBot v3.0.1 by juzraai | https://github.com/juzraai/dijnet-bot
2024-01-25 3:42:31 PM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak
2024-01-25 3:42:31 PM | Kész-lista beolvasása: /mnt/pve/SMB/Számlák/szamlak/kesz.txt
2024-01-25 3:42:31 PM | 67 db számla van a kimeneti mappában
2024-01-25 3:42:31 PM | Könyvtár létrehozása: /mnt/pve/SMB/Számlák/szamlak/.temp
2024-01-25 3:42:31 PM | Bejelentkezés...
2024-01-25 3:42:31 PM | 3s várakozás...
2024-01-25 3:42:34 PM | POST https://www.dijnet.hu/ekonto/login/login_check_password
2024-01-25 3:42:40 PM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012534240__login_login_check_password.html
2024-01-25 3:42:40 PM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012534240__login_login_check_password.cookies
2024-01-25 3:42:40 PM | Bejelentkezve: cs.........
2024-01-25 3:42:40 PM | Számlák keresése...
2024-01-25 3:42:40 PM | 3s várakozás...
2024-01-25 3:42:43 PM | GET https://www.dijnet.hu/ekonto/control/szamla_search
2024-01-25 3:42:44 PM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012534244__control_szamla_search.html
2024-01-25 3:42:44 PM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012534244__control_szamla_search.cookies
2024-01-25 3:42:44 PM | 3s várakozás...
2024-01-25 3:42:47 PM | POST https://www.dijnet.hu/ekonto/control/szamla_search_submit
2024-01-25 3:42:47 PM | HTML fájl kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012534247__control_szamla_search_submit.html
2024-01-25 3:42:47 PM | Sütik kiírása: /mnt/pve/SMB/Számlák/szamlak/.temp/2024012534247__control_szamla_search_submit.cookies
2024-01-25 3:42:47 PM | 0 db számla van a rendszerben: 0 db új, 0 db lementve korábban
2024-01-25 3:42:47 PM | 0 db új számla lementve!

**Comment by juzraai** [comment]
Köszi az infót! Ez viszont már egy másik, új probléma, amit ma jeleztek már mások is: #35. Hamarosan foglalkozom vele.
